---
title: "Reproducible documents"
author: "Olivia Klatt"
format: html
---

```{r setup}
#| include: false
library(tidyverse)
nhanes_small <- read_csv(here::here("data/nhanes_small.csv"))
```

## Table of results

```{r mean-age-bmi-table}
#| echo: false
#| warning: false
#| message: false
nhanes_small %>%
  filter(!is.na(diabetes)) %>%
  group_by(
    diabetes,
    education
  ) %>%
  summarize(
    max_bmi = max(bmi,
      na.rm = TRUE
    ),
    min_bmi = min(bmi,
      na.rm = TRUE
    )
  ) %>%
  ungroup() %>%
  knitr::kable(caption = "Mean values of Age and BMI for each diabetes and education status")
```


to put in code use code chunk, can always only have 1 r setup so you dont need to reload packages all the time, hashtag means header so dotn use for comments


```{r}
2 + 2
```

## Prettier table
```{r prettier-table}
#| echo: false
nhanes_small %>%
  filter(!is.na(diabetes), !is.na(education)) %>%
  group_by(diabetes, education) %>%
  summarise(
    mean_age = mean(age, na.rm = TRUE),
    mean_bmi = mean(bmi, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  mutate(
    # Task 2a.
    mean_age = round(mean_age, digits = 1),
    mean_bmi = round(mean_bmi, digits = 1),
    # Task 2b.
    education = str_to_sentence(education)
  ) %>%
  rename(
    # Task 3.
    "Diabetes Status" = diabetes,
    "Education" = education,
    "Mean Age" = mean_age,
    "Mean BMI" = mean_bmi
  ) %>%
  knitr::kable(caption = "Mean values of Age and BMI for each education and diabetes status.")
```
